
INSERT INTO public.questoes (disciplina, assunto, dificuldade, enunciado, alt_a, alt_b, alt_c, alt_d, alt_e, gabarito, comentario) VALUES
-- Lei nº 2.578/2012 (Estatuto dos Militares do TO)
('Lei nº 2.578/2012', 'Hierarquia e Disciplina', 'Médio',
'De acordo com a Lei nº 2.578/2012 do Estado do Tocantins, que dispõe sobre o Estatuto dos Militares, a hierarquia militar é a ordenação da autoridade em níveis diferentes. Sobre o tema, assinale a alternativa CORRETA:',
'A hierarquia militar é estabelecida exclusivamente pela antiguidade no posto ou graduação.',
'A disciplina é a rigorosa observância e o acatamento integral das leis, regulamentos, normas e disposições.',
'O militar estadual que se encontra em inatividade está dispensado do cumprimento dos preceitos disciplinares.',
'A precedência entre militares de mesmo posto ou graduação é determinada unicamente pela data de nascimento.',
'A hierarquia e a disciplina são aplicáveis apenas durante o serviço ativo.',
1, 'Conforme o Art. 14 da Lei nº 2.578/2012, a disciplina é a rigorosa observância e o acatamento integral das leis, regulamentos, normas e disposições que fundamentam o organismo militar e coordenam seu funcionamento regular e harmônico.'),

('Lei nº 2.578/2012', 'Direitos dos Militares', 'Fácil',
'Segundo a Lei nº 2.578/2012, são direitos dos militares estaduais do Tocantins, EXCETO:',
'Uso das designações hierárquicas.',
'Estabilidade quando preenchidos os requisitos legais.',
'Percepção de remuneração.',
'Liberdade irrestrita de manifestação política partidária.',
'Assistência médico-hospitalar para si e seus dependentes.',
3, 'Conforme a Lei nº 2.578/2012, os militares estaduais não possuem liberdade irrestrita de manifestação político-partidária. Ao contrário, são vedadas atividades político-partidárias aos militares da ativa.'),

('Lei nº 2.578/2012', 'Ingresso na Corporação', 'Médio',
'Sobre o ingresso na Polícia Militar do Tocantins, conforme a Lei nº 2.578/2012, é CORRETO afirmar que:',
'O ingresso pode ocorrer independentemente de concurso público.',
'A idade máxima para ingresso é de 40 anos.',
'O ingresso na PMTO dar-se-á voluntariamente, mediante concurso público.',
'Estrangeiros residentes no Brasil podem ingressar na PMTO.',
'O ingresso independe de aptidão física e mental.',
2, 'A Lei nº 2.578/2012 estabelece que o ingresso na PMTO dar-se-á voluntariamente, mediante concurso público de provas ou de provas e títulos, observados os requisitos legais.'),

('Lei nº 2.578/2012', 'Situação de Atividade e Inatividade', 'Difícil',
'A respeito da passagem do militar estadual do Tocantins para a inatividade, nos termos da Lei nº 2.578/2012, assinale a alternativa INCORRETA:',
'A transferência para a reserva remunerada pode ser voluntária ou ex officio.',
'A reforma é a situação de inatividade definitiva.',
'O militar reformado pode retornar ao serviço ativo a qualquer tempo.',
'A passagem à situação de inatividade pode decorrer de incapacidade definitiva.',
'O militar na reserva remunerada pode ser convocado em situações excepcionais.',
2, 'A reforma é situação definitiva de inatividade. O militar reformado NÃO pode retornar ao serviço ativo, diferentemente do militar na reserva remunerada que pode ser convocado em casos excepcionais.'),

('Lei nº 2.578/2012', 'Deveres Militares', 'Fácil',
'Segundo a Lei nº 2.578/2012, constituem deveres dos militares estaduais do Tocantins:',
'Dedicação exclusiva ao serviço, sendo proibido qualquer outro vínculo empregatício em todos os casos.',
'O culto aos símbolos nacionais e o respeito à dignidade da pessoa humana.',
'A obrigação de cumprir apenas ordens emanadas de superiores de mesmo posto.',
'A dispensa de continência quando fora de serviço.',
'O dever de sigilo se aplica apenas durante o período de serviço ativo.',
1, 'A Lei nº 2.578/2012 estabelece como deveres dos militares estaduais o culto aos símbolos nacionais, o respeito à dignidade da pessoa humana, e a dedicação integral ao serviço policial militar.'),

-- LC nº 128/2021
('LC nº 128/2021', 'Promoção de Oficiais', 'Difícil',
'De acordo com a Lei Complementar nº 128/2021 do Tocantins, que dispõe sobre promoções de oficiais e praças da PMTO, a promoção por merecimento considera:',
'Exclusivamente o tempo de serviço no posto ou graduação.',
'Apenas os cursos realizados pelo militar.',
'Conjunto de atributos que distinguem o militar entre seus pares, incluindo cursos, conduta e desempenho profissional.',
'Somente a avaliação do comandante-geral.',
'A antiguidade como critério único e suficiente.',
2, 'A LC nº 128/2021 estabelece que a promoção por merecimento leva em conta o conjunto de atributos que distinguem o militar entre seus pares, considerando cursos, conduta militar, desempenho profissional e outros critérios definidos em lei.'),

('LC nº 128/2021', 'Critérios de Antiguidade', 'Médio',
'Nos termos da LC nº 128/2021, sobre a promoção por antiguidade na PMTO, é CORRETO afirmar:',
'A antiguidade é contada apenas a partir da data de promoção ao posto atual.',
'A antiguidade em cada posto ou graduação é contada a partir da data de assinatura do ato de promoção.',
'O critério de desempate entre militares de mesma antiguidade é a idade.',
'A antiguidade é irrelevante para fins de promoção.',
'Militares promovidos por merecimento perdem a contagem de antiguidade anterior.',
1, 'Conforme a LC nº 128/2021, a antiguidade em cada posto ou graduação é contada a partir da data estabelecida no ato de promoção, servindo como critério objetivo para as promoções por antiguidade.'),

('LC nº 128/2021', 'Quadro de Acesso', 'Difícil',
'Sobre o Quadro de Acesso por Merecimento (QAM) previsto na LC nº 128/2021, assinale a alternativa CORRETA:',
'O QAM é elaborado anualmente pelo Governador do Estado.',
'A inclusão no QAM depende exclusivamente da vontade do militar.',
'O QAM é organizado pela Comissão de Promoções com base em critérios objetivos definidos em lei.',
'O QAM dispensa a análise de fichas disciplinares.',
'Militares com punições disciplinares graves são automaticamente incluídos no QAM.',
2, 'A LC nº 128/2021 prevê que o QAM é organizado pela Comissão de Promoções, seguindo critérios objetivos que incluem análise de fichas disciplinares, cursos realizados e desempenho profissional.'),

-- Lei nº 2.575/2012
('Lei nº 2.575/2012', 'Organização da PMTO', 'Fácil',
'Conforme a Lei nº 2.575/2012, que dispõe sobre a organização básica da PMTO, é CORRETO afirmar que:',
'A PMTO é força auxiliar e reserva do Exército Brasileiro.',
'A PMTO é subordinada diretamente ao Ministério da Defesa.',
'A PMTO possui autonomia administrativa plena, independente do Poder Executivo.',
'A PMTO não integra o sistema de segurança pública do Estado.',
'A PMTO é vinculada ao Poder Judiciário estadual.',
0, 'Conforme a Lei nº 2.575/2012 e a Constituição Federal, a PMTO é força auxiliar e reserva do Exército Brasileiro, subordinada ao Governador do Estado e integrante do sistema de segurança pública.'),

('Lei nº 2.575/2012', 'Competências da PMTO', 'Médio',
'São competências da Polícia Militar do Tocantins, segundo a Lei nº 2.575/2012:',
'Exercer exclusivamente atividades de polícia judiciária.',
'O policiamento ostensivo e a preservação da ordem pública.',
'A investigação criminal de forma concorrente com a Polícia Civil.',
'Apenas a escolta de presos e segurança externa de presídios.',
'A fiscalização tributária estadual.',
1, 'A Lei nº 2.575/2012 estabelece como competência primordial da PMTO o policiamento ostensivo e a preservação da ordem pública, conforme previsto na Constituição Federal e Estadual.'),

('Lei nº 2.575/2012', 'Comando-Geral', 'Médio',
'Sobre o Comando-Geral da PMTO, nos termos da Lei nº 2.575/2012, é CORRETO afirmar:',
'O Comando-Geral pode ser exercido por qualquer oficial superior.',
'O Comandante-Geral é nomeado pelo Presidente da República.',
'O Comandante-Geral é nomeado pelo Governador do Estado, dentre os oficiais da ativa do último posto.',
'O cargo de Comandante-Geral é eletivo entre os coronéis da ativa.',
'O Comandante-Geral acumula obrigatoriamente o cargo de Secretário de Segurança.',
2, 'A Lei nº 2.575/2012 prevê que o Comandante-Geral da PMTO é nomeado pelo Governador do Estado, devendo ser escolhido dentre os oficiais da ativa do último posto da corporação.'),

-- CPPM (Arts. 8º-28º e 243º-253º)
('CPPM', 'Polícia Judiciária Militar', 'Difícil',
'De acordo com o Código de Processo Penal Militar (arts. 8º a 28º), sobre a polícia judiciária militar, assinale a alternativa CORRETA:',
'A polícia judiciária militar é exercida exclusivamente por delegados de polícia.',
'O Inquérito Policial Militar (IPM) pode ser instaurado de ofício pela autoridade militar competente.',
'O prazo para conclusão do IPM é de 60 dias, improrrogável.',
'O indiciado em IPM tem direito a advogado apenas na fase judicial.',
'O IPM é peça obrigatória para o oferecimento da denúncia.',
1, 'Conforme o Art. 9º do CPPM, o Inquérito Policial Militar pode ser instaurado de ofício pela autoridade militar que tiver conhecimento de infração penal militar, por determinação superior, ou mediante requerimento.'),

('CPPM', 'Inquérito Policial Militar', 'Médio',
'Sobre o Inquérito Policial Militar (IPM), conforme os artigos 9º a 28º do CPPM, é INCORRETO afirmar:',
'O IPM deve ser concluído em 20 dias se o indiciado estiver preso.',
'O IPM deve ser concluído em 40 dias se o indiciado estiver solto.',
'O encarregado do IPM deve ter posto superior ao do indiciado.',
'O IPM pode ser arquivado pela autoridade militar sem manifestação do Ministério Público.',
'O IPM é peça informativa e não contraditória.',
3, 'O arquivamento do IPM não pode ser determinado unilateralmente pela autoridade militar. Compete ao Ministério Público requerer o arquivamento ao juiz competente, conforme as disposições do CPPM.'),

('CPPM', 'Processo Penal Militar - Procedimentos', 'Difícil',
'Nos termos dos artigos 243º a 253º do CPPM, sobre o processo de deserção, é CORRETO afirmar:',
'A deserção é crime que independe de prazo de ausência.',
'O termo de deserção é lavrado após o prazo de graça.',
'O desertor que se apresenta voluntariamente não responde a processo.',
'A deserção de oficial é processada de forma idêntica à de praça.',
'O processo de deserção independe de instauração de inquérito.',
1, 'Conforme o CPPM, o termo de deserção é lavrado após transcorrido o prazo de graça, que é o período regulamentar concedido ao militar ausente antes de ser considerado desertor.'),

-- RDMETO (Decreto nº 4.994/2014)
('RDMETO', 'Transgressões Disciplinares', 'Difícil',
'Conforme o Decreto nº 4.994/2014 (RDMETO), sobre as transgressões disciplinares e suas classificações, é CORRETO afirmar que:',
'As transgressões disciplinares são classificadas apenas em leves e graves.',
'A embriaguez em serviço é classificada como transgressão média.',
'As transgressões disciplinares são classificadas em leves, médias e graves, conforme sua natureza e repercussão.',
'O militar que comete transgressão leve está isento de qualquer punição disciplinar.',
'A classificação das transgressões independe das circunstâncias em que foram praticadas.',
2, 'O RDMETO classifica as transgressões disciplinares em leves, médias e graves, levando em consideração a natureza dos fatos, as circunstâncias que os cercaram e a repercussão no âmbito da corporação.'),

('RDMETO', 'Punições Disciplinares', 'Médio',
'Segundo o RDMETO (Decreto nº 4.994/2014), as punições disciplinares aplicáveis aos militares estaduais do Tocantins são:',
'Advertência, repreensão, detenção, prisão e exclusão a bem da disciplina.',
'Apenas advertência e prisão.',
'Multa, suspensão e demissão.',
'Advertência, repreensão e reforma compulsória.',
'Detenção, prisão e expulsão sumária.',
0, 'O RDMETO prevê como punições disciplinares: advertência, repreensão, detenção, prisão e exclusão a bem da disciplina, aplicáveis conforme a gravidade da transgressão e os antecedentes do transgressor.'),

('RDMETO', 'Comportamento Militar', 'Fácil',
'De acordo com o RDMETO, as classificações de comportamento militar são:',
'Bom e mau.',
'Excepcional, ótimo, bom, regular e mau.',
'Excelente e insuficiente.',
'Apenas bom, regular e insuficiente.',
'Superior, médio e inferior.',
1, 'O RDMETO classifica o comportamento militar em excepcional, ótimo, bom, regular e mau, de acordo com o número e a natureza das punições sofridas pelo militar dentro de determinado período.'),

('RDMETO', 'Recursos Disciplinares', 'Difícil',
'Sobre os recursos disciplinares previstos no RDMETO, assinale a alternativa CORRETA:',
'Não cabe recurso contra punição disciplinar.',
'O recurso deve ser interposto em até 30 dias após a publicação da punição.',
'O militar punido pode interpor pedido de reconsideração à autoridade que aplicou a punição.',
'Apenas oficiais superiores podem interpor recursos disciplinares.',
'O recurso disciplinar tem efeito suspensivo automático.',
2, 'O RDMETO prevê que o militar punido pode interpor pedido de reconsideração à autoridade que aplicou a punição, dentro do prazo regulamentar, expondo as razões de fato e de direito que justifiquem a revisão.'),

('RDMETO', 'Sindicância', 'Médio',
'Nos termos do RDMETO, sobre a sindicância, é CORRETO afirmar:',
'A sindicância é obrigatória antes de qualquer punição disciplinar.',
'A sindicância pode ser dispensada quando a transgressão é flagrante.',
'A sindicância é conduzida exclusivamente por oficiais superiores.',
'O sindicado não tem direito à defesa durante a sindicância.',
'A sindicância tem prazo indeterminado para conclusão.',
1, 'Conforme o RDMETO, a sindicância pode ser dispensada quando a transgressão disciplinar é flagrante e confessa, sendo nestes casos aplicada a punição diretamente pela autoridade competente.'),

('Lei nº 2.578/2012', 'Remuneração', 'Médio',
'Sobre a remuneração dos militares estaduais do Tocantins, conforme a Lei nº 2.578/2012, é CORRETO afirmar:',
'O soldo é a parcela variável da remuneração.',
'O soldo é a parcela básica da remuneração, irredutível, fixada em lei.',
'As gratificações são devidas independentemente de previsão legal.',
'O militar na reserva não percebe qualquer remuneração.',
'O soldo pode ser reduzido por ato administrativo do Comandante-Geral.',
1, 'A Lei nº 2.578/2012 estabelece que o soldo é a parcela básica da remuneração do militar, sendo irredutível e fixado em lei específica.');
